# Generated by Django 4.2.4 on 2023-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('time_length', models.CharField(max_length=100)),
                ('rating_critics', models.CharField(max_length=100)),
                ('rating_audience', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
    ]
